In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [3]:
a= np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
a.shape

(2, 3)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

2

## Creando array

In [10]:
vector_unos = np.ones(10,dtype='int64')
print(vector_unos)

[1 1 1 1 1 1 1 1 1 1]


In [12]:
matriz_unos=np.ones((3,3),dtype='int64')
print(matriz_unos)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
c=matriz_unos.astype(np.float64)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matriz_zeros=np.zeros((5,5))
print(matriz_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.linspace(0,10,3)##divide el rango 0 a 10 en 3

array([ 0.,  5., 10.])

In [16]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
matriz=np.full((2,5),8)
print(matriz)

matriz_zeros_como = np.zeros_like(matriz)## copia las dimensiones y el tipo de dato
print(matriz_zeros_como)

[[8 8 8 8 8]
 [8 8 8 8 8]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.full(5,1.4)

array([1.4, 1.4, 1.4, 1.4, 1.4])

In [30]:
np.full(5,1.4).astype(int)

array([1, 1, 1, 1, 1])

In [31]:
np.full(5,7,dtype=str)

array(['7', '7', '7', '7', '7'], dtype='<U1')

In [ ]:
## crea los nuemros del 10 al 50
array =np.arange(10,50,5)
print(array)
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print('='*100)
#### crea matriz
matriz_zeros= np.zeros((3,4))
identidad=np.eye(3)
print(matriz_zeros)
print(identidad)
print('='*100)
### genera 7 valors
arr=np.linspace(-1,1,7)
print(arr)
print('='*100)
## convierte el priemr array
array_flotante=array.astype('float32')
print(array_flotante)
print(array_flotante.dtype)
print(array_flotante.itemsize)## cuantos bites va a ocupar

[10 15 20 25 30 35 40 45]
(8,)
1
int64
8
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.        ]
[10. 15. 20. 25. 30. 35. 40. 45.]
float32
4


In [ ]:
arr=np.arange(0,16,1)
matriz=arr.reshape((4,4))## para redimensionar
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [45]:
matriz[1,1]

np.int64(5)

In [46]:
matriz[1,:]

array([4, 5, 6, 7])

In [47]:
matriz[:,-1]

array([ 3,  7, 11, 15])

In [48]:
matriz[3,3]

np.int64(15)

In [51]:
vector=np.arange(0,10,1)
print(vector)
vista=vector[6:]
print(vista)

vista[-1]=1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [ ]:
print(vector)### yo no modifique vector pero si vista pero igual se modifica porque comparte la misma direccion

[   0    1    2    3    4    5    6    7    8 1000]


In [53]:
vector=np.arange(0,10,1)
print(vector)
vista=vector[6:].copy()
print(vista)
vista[-1]=1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [54]:
print(vector)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
a= np.array([1.0,4.0,5.0])
np.clip(a,2,5)

array([2., 4., 5.])

In [58]:
a =  np.array([1.0,4.0,9.0,np.nan])
np.isnan(a).sum()##para contar cuantos True tiene el array

np.int64(1)

In [59]:
np.isclose(4,6,2)

np.True_

In [68]:
array=np.array([1,2,5,4,0,8,7])

In [ ]:
array.max()

np.int64(8)

: 

In [71]:
array.argmax()

np.int64(5)