In [4]:
import numpy as np
print(np.__version__)

2.5.1


### Lista VS Array

In [5]:
lista = [1,2,3,5]
type(lista)

list

In [6]:
lista *2

[1, 2, 3, 5, 1, 2, 3, 5]

In [7]:
### lista no tiene atajos para trabajar numeros o operaciones matematicas y el array si

In [8]:
array= np.array([1,2,3,5])
type(array)

numpy.ndarray

In [9]:
array *2 

array([ 2,  4,  6, 10])

In [10]:
lista = [1,2,3,5]
arr_lista=np.array(lista)
print(arr_lista)
print(type(arr_lista))

[1 2 3 5]
<class 'numpy.ndarray'>


In [11]:
arr_lista.dtype##para saber el tipo de los elementos

dtype('int64')

In [12]:
lista_decimales=[1.0,2.1,2.4,5.6]
arr_lista=np.array(lista_decimales)
arr_lista.dtype

dtype('float64')

In [13]:
lista = [1,2,3,5]
arr_lista=np.array(lista,dtype='float64')
print(arr_lista)
arr_lista.dtype

[1. 2. 3. 5.]


dtype('float64')

### Convertir tipo de datos de mi array

In [14]:
lista = [1,2,3,5]
arr_lista=np.array(lista)
print(arr_lista)
arr_lista.dtype

[1 2 3 5]


dtype('int64')

In [15]:
arr_float= arr_lista.astype('float64')
print(arr_float)
arr_float.dtype

[1. 2. 3. 5.]


dtype('float64')

In [16]:
arr_str= arr_lista.astype('str')
print(arr_str)
arr_str.dtype

['1' '2' '3' '5']


dtype('<U21')

## Dimensiones

In [17]:
# Scalar
scalar=np.array(50)
print(scalar)
print(type(scalar))
print(scalar.ndim)

50
<class 'numpy.ndarray'>
0


In [18]:
##Vector
vector= np.array([1,2,3,4])
print(vector.ndim)

1


In [ ]:
vector.shape

(4,)

: 

In [ ]:
# Matriz
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


## Generacion de numeros aleatorios

In [ ]:
np.arange(0,20,2) ##0 inicio, 20 final, 2 pasos de 2 a 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [ ]:
np.ones((10,10), dtype='int64')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.ones((10,10,2), dtype='int64')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])